### PR TITLE
[WIP] Integration of multi-dimensional analysis using RootInteractive ND pipeline

### PR DESCRIPTION
**Pull request by ehellbar**
…ysis

### CODE REVIEW

**Comment by ehellbar** [comment]
Hello @ginnocen ,

I dumped a small data frame with pickle for test purposes.
The test root file with the TTree is 34 MB, the outputfile by pickle is 813 MB. That's a factor more 24 in size. 

The root file with the output needed to create the the 5D histograms and pdfmaps is 3.1 GB for 4000 validation entries on the smallest grid size. So even reducing the number of validation data, the file if dumped by pickle will be too big.

Cheers,
Ernst

**Comment by ehellbar** [comment]
Hello @ginnocen ,
btw I think I mixed it up. It is the generation of the histograms which takes up all the memory space, the writing process itself is ok I think.
Cheers,
Ernst

**Comment by ehellbar** [comment]
Hello @ginnocen again,
I think I know what the problem is. The df I use is simply too large (4000 validation maps). It, or a query, is copied a couple times, some of which are unavoidable (like in return statements I guess). I will reduce the size of the df to 1000 events and see how it looks then.

**Comment by ehellbar** [comment]
Hello @ginnocen ,
for now, I think this should be fine as a first version. Once there are updated algorithms for the performance map creation (skipping histogramming), we can merge them in a second PR. Let me know what you think.
Cheer,
Ernst

**Comment by ehellbar** [comment]
Hello @ginnocen , 
can we merge this now to avoid more manual merging after other PRs? It does not interfere with the workflow in any way, except for the addition of Nev in the suffix and small modification in the model repo structure (last commit).
Cheers,
Ernst

**Comment by ginnocen** [comment]
Ciao Ernst yes sure. Sorry for the delay I am going now through the changes and give you feedback.

**Pull request closed without merging**
